INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (1, 1, NULL, 'C', NULL, NULL, 0, 'Privacy Statement', NULL, NULL, 'Privacy Statement\r\n', NULL, 'U', 'tago', '2018-11-13 14:24:30', NULL, NULL);
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (2, 1, NULL, 'C', NULL, NULL, 1, 'Privacy Statement', NULL, NULL, 'Privacy Statement1', NULL, 'U', 'tago', '2018-11-13 14:29:45', NULL, '2018-11-13 14:31:10');
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (3, 1, NULL, 'C', NULL, NULL, 0, 'terms and conditions', NULL, NULL, 'terms and conditions', NULL, 'U', 'tago', '2018-11-13 14:30:25', NULL, NULL);
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (4, 1, NULL, 'C', NULL, NULL, 1, 'terms and conditions', NULL, NULL, 'terms and conditions1', NULL, 'U', 'tago', '2018-11-13 14:30:41', NULL, '2018-11-13 14:31:13');
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (5, 1, NULL, 'C', NULL, NULL, 2, 'terms and conditions', NULL, NULL, 'terms and conditions3', NULL, 'U', 'tago', '2018-11-13 16:13:58', NULL, '2018-11-13 16:52:48');
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (6, 1, NULL, 'C', NULL, NULL, 3, 'terms and conditions', NULL, NULL, 'new terms', NULL, 'U', 'tago', '2018-11-13 16:28:13', NULL, '2018-11-13 16:52:51');
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (7, 1, NULL, 'C', NULL, NULL, 2, 'Privacy Statement', NULL, NULL, 'new privacy', NULL, 'U', 'tago', '2018-11-13 16:28:46', NULL, '2018-11-13 16:52:57');
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (8, 1, NULL, 'C', NULL, NULL, 4, 'terms and conditions', NULL, NULL, 'xaxaxaxx', NULL, 'U', 'tago', '2018-11-13 16:32:55', NULL, NULL);
INSERT INTO `ts_comm_contents` (`IDX`, `SITE_SEQ`, `C_TYPE`, `TB_NAME`, `TB_IDX`, `SORT_NUM`, `VERSION`, `TITLE`, `SUB_TITLE`, `LINK_URL`, `CONTENTS`, `VIEW_CNT`, `USE_FLAG`, `REG_USER`, `REG_DATE`, `MOD_USER`, `MOD_DATE`) VALUES (9, 1, NULL, 'C', NULL, NULL, 3, 'Privacy Statement', NULL, NULL, 'xexexexexexe', NULL, 'U', 'tago', '2018-11-13 16:33:13', NULL, NULL);
